from __future__ import annotations


CONTROLLER_BASELINE = {
    "loc": 7723,
    "method_count": 369,
    "public_method_count": 23,
    "private_method_count": 346,
    "stored_field_count": 152,
    "mss_grab_call_count": 7,
}


CONTROLLER_STAGE_EXPECTED = {
    "loc": 5893,
    "method_count": 390,
    "public_method_count": 29,
    "private_method_count": 361,
    "stored_field_count": 115,
    "mss_grab_call_count": 0,
}


PUBLIC_METHODS = frozenset(
    {
        "can_run_actions",
        "capture_bar_preview_images",
        "cleanup",
        "consume_emergency_stop_requested",
        "current_bar_detection_regions",
        "emergency_stop",
        "install_console_redirect",
        "is_closed",
        "is_key_capture_blocking_actions",
        "notify_minimap_cruise_toggle",
        "poll_control_hotkeys",
        "potion_priority_defer_until",
        "reset_experience_statistics",
        "request_control_release",
        "runtime_port",
        "send_control_runtime",
        "set_auto_drink_challenge_paused",
        "set_auto_drink_enabled",
        "set_minimap_cruise_toggle_handler",
        "set_pickup_enabled",
        "start_control_runtime",
        "should_defer_periodic_item_for_potion",
        "toggle_auto_drink_enabled",
        "toggle_experience_efficiency",
        "toggle_pickup_enabled",
        "toggle_scripts_enabled",
        "drain_control_runtime_statuses",
        "control_runtime_alive",
        "update",
    }
)


PUBLIC_METHOD_SIGNATURES = {
    "__init__": "(self, is_target_window_active: 'Callable[[], bool]', settings: 'AutoPotionSettings | None' = None, target_window_provider: 'Callable[[], int] | None' = None, gui: 'object | None' = None, start_control_hotkey_worker: 'bool' = True, start_potion_action_worker: 'bool' = True, experience_executor: 'object | None' = None, runtime_processes_enabled: 'bool' = True, save_settings_on_cleanup: 'bool' = True, experience_only_runtime: 'bool' = False) -> 'None'",
    "install_console_redirect": "(self) -> 'None'",
    "is_closed": "(self) -> 'bool'",
    "can_run_actions": "(self) -> 'bool'",
    "set_auto_drink_enabled": "(self, enabled: 'bool') -> 'bool'",
    "set_auto_drink_challenge_paused": "(self, paused: 'bool') -> 'None'",
    "set_pickup_enabled": "(self, enabled: 'bool') -> 'bool'",
    "poll_control_hotkeys": "(self) -> 'None'",
    "is_key_capture_blocking_actions": "(self) -> 'bool'",
    "consume_emergency_stop_requested": "(self) -> 'bool'",
    "set_minimap_cruise_toggle_handler": "(self, handler: 'Callable[[], None] | None') -> 'None'",
    "toggle_pickup_enabled": "(self) -> 'None'",
    "toggle_auto_drink_enabled": "(self) -> 'None'",
    "toggle_scripts_enabled": "(self) -> 'None'",
    "notify_minimap_cruise_toggle": "(self, enabled: 'bool', changed: 'bool', message: 'str') -> 'None'",
    "toggle_experience_efficiency": "(self) -> 'None'",
    "emergency_stop": "(self) -> 'None'",
    "update": "(self, now: 'float', *, pump_gui: 'bool' = True) -> 'None'",
    "reset_experience_statistics": "(self) -> 'bool'",
    "should_defer_periodic_item_for_potion": "(self, now: 'float') -> 'bool'",
    "potion_priority_defer_until": "(self, now: 'float', hp_percent: 'float | None' = None, mp_percent: 'float | None' = None) -> 'float'",
    "current_bar_detection_regions": "(self) -> 'dict[str, tuple[int, int, int, int] | None]'",
    "capture_bar_preview_images": "(self, make_target_topmost: 'bool' = False) -> 'dict[str, dict[str, object]]'",
    "cleanup": "(self) -> 'None'",
    "start_control_runtime": "(self, worker_target, *worker_args: 'object') -> 'bool'",
    "send_control_runtime": "(self, command: 'ControlCommand') -> 'None'",
    "request_control_release": "(self, command: 'ControlCommand') -> 'None'",
    "drain_control_runtime_statuses": "(self, limit: 'int' = 64) -> 'list[object]'",
    "control_runtime_alive": "(self) -> 'bool'",
}


CONSTRUCTOR_BASELINE_PARAMETERS = (
    "self",
    "is_target_window_active: 'Callable[[], bool]'",
    "settings: 'AutoPotionSettings | None' = None",
    "target_window_provider: 'Callable[[], int] | None' = None",
    "gui: 'object | None' = None",
    "start_control_hotkey_worker: 'bool' = True",
    "start_potion_action_worker: 'bool' = True",
    "experience_executor: 'object | None' = None",
    "runtime_processes_enabled: 'bool' = True",
    "save_settings_on_cleanup: 'bool' = True",
    "experience_only_runtime: 'bool' = False",
)


CONSTRUCTOR_STAGE4_KEYWORD_ONLY_PARAMETERS = (
    "runtime_process_factory: 'RuntimeProcessFactory | None' = None",
    "media_sink: 'RuntimeMediaSink | None' = None",
)


STORED_FIELDS = frozenset(
    {
        "_cleanup_completed",
        "_cleanup_completed_steps",
        "_cleanup_in_progress",
        "auto_drink_challenge_paused",
        "auto_drink_disable_hold_started_at",
        "auto_drink_enabled",
        "auto_drink_potion_option_snapshot",
        "bottom_bar_client_bounds",
        "bottom_bar_regions_at",
        "control_hotkey_coordinator",
        "direct_bar_failure_count",
        "emergency_stop_requested",
        "experience_10m_checkpoint_capture",
        "experience_10m_checkpoint_tooltip_failed",
        "experience_baseline_calibration",
        "experience_baseline_calibration_attempts",
        "experience_baseline_cursor_position",
        "experience_capture_coordinator",
        "experience_initial_tooltip_baseline_started_at",
        "experience_ocr_burst",
        "experience_only_runtime",
        "experience_pause_started_at",
        "experience_reader",
        "experience_text_region_bar_crop_left_ratios",
        "experience_tooltip_baseline_failed",
        "experience_tooltip_ocr_failures",
        "experience_total_paused_seconds",
        "experience_tracker",
        "fade_guard_hits",
        "fade_guard_until",
        "gameplay_hud_active",
        "gui",
        "hud_bar_detector",
        "hp_out_of_potion_hold",
        "hp_pending_potion_send_at",
        "hp_pending_potion_send_percent",
        "hp_potion_damage_pressure_active",
        "hp_potion_effect_attempts",
        "hp_potion_held_vk",
        "hp_potion_hold_refreshed_at",
        "hp_potion_last_no_effect_counted_at",
        "hp_potion_last_observed_percent",
        "hp_potion_no_effect_count",
        "hp_potion_recent_damage_at",
        "hp_potion_recent_samples",
        "is_target_window_active",
        "last_action",
        "last_applied_experience_status_signature",
        "last_applied_potion_status_signature",
        "last_completed_experience_ocr_signature",
        "last_direct_bar_failure_reason",
        "last_direct_bar_failure_warning_at",
        "last_error_at",
        "last_experience_mouse_idle_delay_log_at",
        "last_experience_mouse_idle_status_at",
        "last_experience_mouse_idle_status_key",
        "last_experience_ocr_error_at",
        "last_experience_ocr_error_reason",
        "last_experience_tooltip_capture_debug",
        "last_experience_tooltip_capture_skip",
        "last_failed_experience_ocr_signature",
        "last_hp_drink_at",
        "last_mp_drink_at",
        "last_potion_blocked_sound_at",
        "last_potion_check_sound_at",
        "last_runtime_experience_alert_status",
        "last_runtime_potion_status_at",
        "last_target_hwnd",
        "last_unstable_bar_at",
        "minimap_cruise_toggle_handler",
        "mouse_activity_observer",
        "mp_out_of_potion_hold",
        "mp_pending_potion_send_at",
        "mp_pending_potion_send_percent",
        "mp_potion_damage_pressure_active",
        "mp_potion_effect_attempts",
        "mp_potion_held_vk",
        "mp_potion_hold_refreshed_at",
        "mp_potion_last_no_effect_counted_at",
        "mp_potion_last_observed_percent",
        "mp_potion_no_effect_count",
        "mp_potion_recent_damage_at",
        "mp_potion_recent_samples",
        "next_capture_at",
        "next_experience_10m_checkpoint_at",
        "next_experience_baseline_calibration_at",
        "next_experience_capture_at",
        "next_settings_save_at",
        "original_stderr",
        "original_stdout",
        "pending_settings_snapshot",
        "pickup_disable_hold_started_at",
        "pickup_enabled",
        "pickup_held_vk",
        "potion_action_worker",
        "potion_send_prevalidated_at",
        "potion_engine",
        "runtime_control_state",
        "runtime_experience_crash_reported",
        "runtime_experience_generation",
        "runtime_potion_action_defer_until",
        "runtime_potion_crash_reported",
        "runtime_potion_generation",
        "runtime_processes",
        "runtime_processes_enabled",
        "runtime_settings_snapshot",
        "runtime_target_hwnd",
        "save_settings_on_cleanup",
        "scripts_enabled",
        "screen_capture_service",
        "settings",
        "target_window_provider",
    }
)


REQUIRED_PRIVATE_METHOD_SHIMS = frozenset(
    {
        "_alert_suspected_no_potion",
        "_apply_potion_status",
        "_apply_runtime_bar_detection_region",
        "_apply_worker_crash",
        "_bar_color_mask",
        "_bar_detection_debug_text",
        "_bar_percent_from_region_snapshot",
        "_bar_run_candidates",
        "_bar_track_right_of_label",
        "_bottom_bar_pair_regions_from_candidates",
        "_bottom_bar_search_areas",
        "_bottom_hud_layout_from_labels",
        "_cache_bottom_bar_client_regions",
        "_cached_bottom_bar_screen_regions_for_current_client",
        "_can_keep_current_bottom_bar_geometry",
        "_can_reuse_stale_bottom_bar_regions",
        "_cancel_experience_baseline_calibration",
        "_capture_bar_percent",
        "_capture_bar_percent_direct",
        "_capture_bar_percent_from_region",
        "_capture_bar_percents",
        "_capture_bar_percents_direct",
        "_capture_confirmed_bar_percent",
        "_capture_experience_tooltip_image",
        "_capture_foreground_client_image",
        "_clear_experience_baseline_calibration_state",
        "_clear_potion_attempt_state",
        "_clear_potion_effect_state",
        "_clear_uncertain_potion_observations",
        "_can_execute_potion_action",
        "_close_media_files",
        "_continue_experience_ocr_burst",
        "_defer_experience_for_potion_priority",
        "_direct_bar_image_from_region",
        "_discard_control_hotkey_messages",
        "_drain_potion_engine_command_results",
        "_drain_runtime_statuses",
        "_emit_direct_bar_failure_warning_if_needed",
        "_enforce_experience_prerequisites",
        "_experience_effective_time",
        "_experience_ocr_image_signature",
        "_experience_ocr_signatures_are_similar",
        "_experience_runtime_has_cached_hud",
        "_experience_runtime_needs_hud_refresh",
        "_experience_text_region",
        "_experience_text_region_bar_crop_left_ratio",
        "_experience_text_regions",
        "_find_bottom_bar_pair_regions",
        "_foreground_client_bounds",
        "_hud_label_template",
        "_is_channel_loading_screen_active",
        "_is_transition_fade_active",
        "_locate_stat_window_exp_roi",
        "_log_unstable_bar",
        "_mark_initial_experience_tooltip_baseline_start",
        "_maybe_drink_hp",
        "_maybe_drink_mp",
        "_pause_experience_clock",
        "_pause_experience_for_inactive_state",
        "_pause_experience_for_missing_hud",
        "_percent_from_bar_mask_result",
        "_play_lie_detector_alert_sound",
        "_play_lie_detector_alert_sound_blocking",
        "_play_media_file",
        "_play_media_file_with_volume",
        "_play_minimap_cruise_toggle_sound",
        "_play_toggle_beep",
        "_process_due_potion_sends",
        "_process_exp_10m_checkpoint",
        "_process_exp_10m_checkpoint_ocr_job",
        "_process_experience_baseline_calibration",
        "_process_experience_ocr_job",
        "_process_pending_auto_drink_disable",
        "_process_pending_pickup_disable",
        "_record_direct_bar_failure",
        "_record_direct_bar_success",
        "_record_potion_effect_attempt",
        "_recover_stale_runtime_potion_process",
        "_refresh_gameplay_hud_state",
        "_register_toggle_hotkey",
        "_release_all_potion_keys",
        "_release_potion_key",
        "_release_pickup_key",
        "_reset_experience_baseline_calibration_attempts",
        "_resume_exp_10m_checkpoint_schedule",
        "_resume_experience_clock",
        "_reuse_cached_bottom_bar_regions_with_direct_sample",
        "_sample_direct_bar_percent_from_image",
        "_sample_direct_bar_percent_from_region",
        "_save_settings_when_idle",
        "_set_bar_detection_debug",
        "_set_gameplay_hud_active",
        "_start_bottom_experience_ocr_capture",
        "_start_experience_tooltip_ocr_capture",
        "_stat_window_fixed_exp_label_template",
        "_stop_experience_ocr_job",
        "_submit_experience_ocr_burst",
        "_sync_control_hotkey_down_states",
        "_sync_pickup_key_state",
        "_sync_registered_control_hotkeys",
        "_target_client_bounds",
        "_toggle_experience_stat_window",
        "_transition_pause_reason",
        "_try_emergency_stop",
        "_try_reset_experience_statistics",
        "_try_toggle_experience_efficiency",
        "_try_toggle_minimap_cruise",
        "_try_toggle_pickup",
        "_try_toggle_scripts_enabled",
        "_unregister_toggle_hotkey",
        "_update_experience_efficiency",
        "_update_potion_engine",
        "_update_potion_effect_watch_cycles",
        "_wait_for_preview_target_ready",
    }
)


REQUIRED_PRIVATE_ATTRIBUTES = frozenset(
    {
        "_initialization_completed",
        "_lie_detector_alert_thread",
        "_media_alias_paths",
    }
)


RESOURCE_OWNERS = {
    "mss": "ScreenCaptureService._backend",
    "gdi_capture": "HudBarDetector.direct_capture_context",
    "control_hotkey_worker": "ControlHotkeyCoordinator.worker",
    "potion_action_worker": "AutoPotionController.potion_action_worker",
    "ocr_executor": "ExperienceCaptureCoordinator.executor",
    "runtime_processes": "AutoPotionController.runtime_processes",
    "mci_aliases": "MediaPlaybackService.alias_paths",
    "lie_detector_thread": "MediaPlaybackService.alert_thread",
}


MSS_GRAB_CALL_SITES = {}

SCREEN_CAPTURE_GRAB_CALL_SITES = {
    "_capture_foreground_client_image": 1,
}


PATCH_POINT_CLASSIFICATIONS = {
    "dynamic_adapter": frozenset(
        {
            "maple_star.controller.ctypes.windll",
            "maple_star.controller.key_down",
            "maple_star.controller.key_up",
            "maple_star.controller.mss.mss",
            "maple_star.controller.save_settings",
            "maple_star.controller.tap_hotkey",
            "maple_star.controller.threading.Thread",
            "maple_star.controller.time.monotonic",
            "maple_star.controller.time.sleep",
            "maple_star.controller.user32.GetAsyncKeyState",
            "maple_star.controller.winsound.Beep",
            "maple_star.controller.winsound.MessageBeep",
            "maple_star.controller.winsound.PlaySound",
            "maple_star.controllers.auto_potion_controller.get_cursor_position",
            "maple_star.controllers.auto_potion_controller.log_exception",
            "maple_star.controllers.auto_potion_controller.log_experience_debug",
            "maple_star.controllers.auto_potion_controller.save_settings",
            "maple_star.controllers.auto_potion_controller.set_cursor_position",
            "maple_star.controllers.auto_potion_controller.sleep_while_pumping_messages",
            "maple_star.controllers.auto_potion_controller.temporary_mouse_input_lock",
            "maple_star.controllers.auto_potion_controller.user32.ClientToScreen",
            "maple_star.controllers.auto_potion_controller.user32.GetClientRect",
            "maple_star.controllers.auto_potion_controller.user32.GetForegroundWindow",
        }
    ),
    "controller_shim": REQUIRED_PRIVATE_METHOD_SHIMS,
    "canonical_reexport": frozenset(
        {
            "AUTO_DRINK_POTION_CHECK_SOUND_PATH",
            "AUTO_DRINK_START_SOUND_PATH",
            "AUTO_DRINK_STOP_SOUND_PATH",
            "AUTO_PICKUP_START_SOUND_PATH",
            "AUTO_PICKUP_STOP_SOUND_PATH",
            "AutoPotionController",
            "BarDetectionDebug",
            "ControlCommand",
            "ControlStatus",
            "ExperienceControl",
            "ExperienceOcrJob",
            "ExperienceStatus",
            "InlineExecutor",
            "LIE_DETECTOR_ALERT_SOUND_PATH",
            "MINIMAP_CRUISE_START_WAV_PATH",
            "MINIMAP_CRUISE_STOP_WAV_PATH",
            "PotionControl",
            "PotionStatus",
            "SettingsUpdated",
            "Shutdown",
            "TargetWindowUpdated",
            "WorkerCrashed",
            "_create_auto_potion_controller",
            "_experience_status_signature",
            "_potion_status_signature",
            "bgra_image_to_ppm_data",
            "loading_screen_metrics",
            "normalize_bar_percent",
        }
    ),
}
