from __future__ import annotations


EXP_SAMPLE_HISTORY_SECONDS = 3600.0
EXP_RATE_MIN_SECONDS = 5.0
EXP_RATE_5M_SECONDS = 300.0
EXP_RATE_10M_SECONDS = 600.0
EXP_RATE_1H_SECONDS = 3600.0
EXP_RATE_5M_HALF_LIFE_SECONDS = 45.0
EXP_RATE_10M_HALF_LIFE_SECONDS = 180.0
EXP_RATE_1H_HALF_LIFE_SECONDS = 600.0
EXP_RATE_5M_SMOOTHING_ALPHA = 0.65
EXP_RATE_10M_SMOOTHING_ALPHA = 0.45
EXP_RATE_1H_SMOOTHING_ALPHA = 0.25
EXP_RATE_FAST_CONVERGENCE_SAMPLE_COUNT = 8
EXP_RATE_FAST_CHANGE_RATIO = 0.20
EXP_RATE_FAST_SMOOTHING_ALPHA = 0.70
EXP_ETA_MIN_CONFIDENCE = 0.25
EXP_ETA_MIN_RATE_PER_SECOND = 1.0
EXP_ETA_MAX_SECONDS = 9999.0 * 3600.0
EXP_LEVEL_WRAP_HIGH_PERCENT = 65.0
EXP_LEVEL_WRAP_LOW_PERCENT = 35.0
EXP_OCR_MIN_SCORE = 0.70
EXP_OCR_ACCEPT_CONFIDENCE = 0.85
EXP_OCR_IMAGE_SCALE = 2
EXP_OCR_PREPARED_SCALE = 3
EXP_OCR_TARGET_HEIGHT = 72
EXP_OCR_MAX_SCALE = 5
EXP_OCR_CONTEXT_PADDING_RATIO = 0.40
EXP_OCR_CONTEXT_MIN_PADDING = 8
EXP_OCR_CONTEXT_MAX_PADDING = 18
EXP_OCR_TEXT_MIN_RATIO = 0.001
EXP_OCR_TEXT_MAX_RATIO = 0.35
EXP_OCR_TEXT_BINARY_MAX_RATIO = 0.90
EXP_OCR_TEXT_ROW_MIN_RATIO = 0.01
EXP_OCR_TEXT_COLUMN_MIN_RATIO = 0.03
EXP_OCR_TEXT_CROP_PADDING_RATIO = 0.18
EXP_OCR_DENSE_BORDER_ROW_MAX_RATIO = 0.72
EXP_OCR_DENSE_BORDER_ROW_PADDING = 1
EXP_OCR_TOP_BORDER_ROW_MAX_RATIO = 0.45
EXP_OCR_TOP_BORDER_MAX_HEIGHT_RATIO = 0.28
EXP_OCR_BINARY_LUMINANCE_MIN = 200.0
EXP_OCR_BINARY_MAX_CHROMA = 65.0
EXP_OCR_GREEN_BACKGROUND_MIN_GREEN = 120.0
EXP_OCR_GREEN_BACKGROUND_MIN_CHROMA = 35.0
EXP_OCR_GREEN_BACKGROUND_MIN_RATIO = 0.02
EXP_OCR_GREEN_BACKGROUND_MIN_BAR_PERCENT = 20.0
EXP_OCR_GREEN_BACKGROUND_MAX_BAR_PERCENT = 97.5
EXP_OCR_GREEN_BACKGROUND_REPLACEMENT = 28
EXP_OCR_MIN_STRUCTURE_SCORE = 1.0
EXP_OCR_TRUSTED_NONBINARY_EXACT_CONFIDENCE = 0.95
EXP_OCR_REPAIRED_PERCENT_MAX_DISAGREEMENT = 0.35
EXP_OCR_REPAIRED_PERCENT_CONFIDENCE_TOLERANCE = 0.05
EXP_OCR_BAR_CROP_LEFT_RATIO = 0.44
EXP_OCR_BAR_GREEN_COLUMN_MIN_RATIO = 0.18
EXP_OCR_BAR_MIN_GREEN_SPAN_RATIO = 0.25
EXP_OCR_BAR_MIN_PARTIAL_GREEN_SPAN_RATIO = 0.025
EXP_OCR_BAR_LEFT_TOUCH_RATIO = 0.04
EXP_OCR_BAR_PERCENT_TOLERANCE = 12.0
EXP_OCR_TIGHT_RIGHT_ROI_MIN_BAR_CROP_LEFT_RATIO = 0.55
EXP_OCR_TIGHT_RIGHT_ROI_MAX_WIDTH = 280
EXP_OCR_TIGHT_RIGHT_ROI_MAX_HEIGHT = 48
EXP_PIXEL_FONT_RECOGNIZER_MIN_CONFIDENCE = 0.95
EXP_PIXEL_FONT_RECOGNIZER_BAR_PERCENT_TOLERANCE = 6.0
EXP_PIXEL_FONT_RECOGNIZER_MAX_ATTEMPTS = 18
EXP_PIXEL_FONT_CONFLICT_ACCEPT_CONFIDENCE = 0.978
EXP_PIXEL_FONT_CONFLICT_ACCEPT_GAP = 0.0012
EXP_PIXEL_FONT_TEMPLATE_SIZE = (48, 32)
EXP_PIXEL_FONT_PERCENT_ALTERNATIVE_SCORE_WINDOW = 0.30
EXP_PIXEL_FONT_PERCENT_MAX_ALTERNATIVES = 8
EXP_PIXEL_FONT_PERCENT_TOPOLOGY_CONFIDENCE = 0.992
EXP_PIXEL_FONT_PERCENT_TOPOLOGY_DEMOTED_CONFIDENCE = 0.936
EXP_PIXEL_FONT_PERCENT_UNRESOLVED_AMBIGUITY_GAP = 0.026
EXP_PIXEL_FONT_SPLIT_PERCENT_REPAIR_CONFIDENCE = 0.982
EXP_PIXEL_FONT_SPLIT_PERCENT_MIN_EXP_CONFIDENCE = 0.84
EXP_PIXEL_FONT_SPLIT_PERCENT_MIN_EXP_AVERAGE_CONFIDENCE = 0.88
EXP_PIXEL_FONT_SPLIT_PERCENT_AMBIGUITY_GAP = 0.08
EXP_PIXEL_FONT_EXP_ALTERNATIVE_SCORE_WINDOW = 0.18
EXP_PIXEL_FONT_EXP_MAX_ALTERNATIVE_POSITIONS = 3
EXP_PIXEL_FONT_EXP_MAX_ALTERNATIVE_CANDIDATES = 24
EXP_PIXEL_FONT_FULL_BAR_PERCENT_MIN = 98.0
EXP_PIXEL_FONT_FULL_BAR_MIN_CONFIDENCE = 0.97
EXP_PIXEL_FONT_NO_BAR_LOW_PERCENT_MAX = 2.0
EXP_PIXEL_FONT_NO_BAR_LOW_PERCENT_MIN_CONFIDENCE = 0.84
EXP_PIXEL_FONT_ZERO_THREE_TOPOLOGY_MARGIN = 0.10
EXP_PIXEL_FONT_ZERO_THREE_TOPOLOGY_BONUS = 0.12
EXP_TOTAL_ESTIMATE_MAX_DEVIATION_RATIO = 0.35
EXP_SINGLE_GAIN_MAX_LEVEL_RATIO = 0.35
EXP_OCR_CONTINUITY_MAX_PERCENT_GAIN_PER_SECOND = 10.0
EXP_OCR_CONTINUITY_MIN_JUMP_PERCENT = 2.0
EXP_OCR_CONTINUITY_LEVEL_UP_PREVIOUS_PERCENT_MIN = EXP_LEVEL_WRAP_HIGH_PERCENT
EXP_OCR_CONTINUITY_LEVEL_UP_CANDIDATE_PERCENT_MAX = EXP_LEVEL_WRAP_LOW_PERCENT
EXP_LEVEL_WRAP_RATE_GRACE_SECONDS = 90.0
EXP_LEVEL_WRAP_RATE_DISPLAY_FLOOR = 10000.0
EXP_GAIN_EXPECTED_TOLERANCE_RATIO = 3.0
EXP_GAIN_MIN_ABSOLUTE_TOLERANCE = 5000
EXP_INITIAL_REBASE_MAX_SAMPLES = 6
EXP_GAIN_RATE_SPIKE_MULTIPLIER = 20.0
EXP_PERCENT_REGRESSION_TOLERANCE = 0.03
EXP_PERCENT_DELTA_TOLERANCE_RATIO = 1.25
EXP_PERCENT_ROUNDING_TOLERANCE_RATIO = 0.0002
EXP_PERCENT_DELTA_MIN_ABSOLUTE_TOLERANCE = 1000
EXP_PERCENT_UNDERGAIN_STRICT_MIN_DELTA = 0.50
EXP_PERCENT_UNDERGAIN_STRICT_MIN_EXPECTED_DELTA = 20000
EXP_PERCENT_UNDERGAIN_STRICT_MIN_RATIO = 0.35
EXP_REBASE_CONFIRM_SECONDS = 20.0
EXP_REBASE_CONFIRM_MAX_PERCENT_DELTA = 0.30
EXP_REBASE_CONFIRM_MAX_LEVEL_RATIO = 0.03
EXP_REBASE_CONFIRM_MIN_ABSOLUTE_DELTA = 8000
EXP_REBASE_TRUSTED_CONFLICT_MIN_CONFIDENCE = 0.90
EXP_REBASE_CONFIRM_MAX_TOTAL_DEVIATION_RATIO = 0.005
EXP_INITIAL_BASELINE_CONFIRM_SECONDS = 20.0
EXP_INITIAL_BASELINE_CONFIRM_MAX_PERCENT_DELTA = 0.30
EXP_INITIAL_BASELINE_CONFIRM_MIN_ABSOLUTE_DELTA = 8000
EXP_INITIAL_BASELINE_CONFIRM_MAX_LEVEL_RATIO = 0.003
EXP_INITIAL_BASELINE_MAX_CANDIDATES = 5
EXP_OUTLIER_REPAIR_MAX_REMOVED_SAMPLES = 3
EXP_OUTLIER_REPAIR_MAX_AGE_SECONDS = 60.0
EXP_OUTLIER_REPAIR_REASON_PREFIX = "離群修正候選"
EXP_RATE_MIN_ACCEPTED_SAMPLE_INTERVAL_SECONDS = 1.0
EXP_LONG_RATE_BLEND_START_SECONDS = 300.0
EXP_LONG_RATE_BLEND_FULL_SECONDS = 3600.0
PADDLEOCR_LANGUAGE = "chinese_cht"
PADDLEOCR_DETECTION_MODEL_NAME = "PP-OCRv5_mobile_det"
PADDLEOCR_RECOGNITION_MODEL_NAME = "PP-OCRv5_mobile_rec"
EXP_STAT_WINDOW_OCR_ACCEPT_CONFIDENCE = 0.80
EXP_STAT_WINDOW_OCR_PREPARED_SCALE = 3
PADDLEOCR_ENV_DEFAULTS = {
    "PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK": "True",
    "GLOG_minloglevel": "2",
    "FLAGS_minloglevel": "2",
    "FLAGS_cpu_math_library_num_threads": "1",
    "OMP_NUM_THREADS": "1",
    "MKL_NUM_THREADS": "1",
    "OPENBLAS_NUM_THREADS": "1",
    "NUMEXPR_NUM_THREADS": "1",
}


__all__ = [name for name in globals() if name.startswith(("EXP_", "PADDLEOCR_"))]
